# Generated by Django 4.0.4 on 2022-04-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.CharField(max_length=5)),
                ('sw', models.CharField(max_length=5)),
                ('pl', models.CharField(max_length=5)),
                ('pw', models.CharField(max_length=5)),
                ('predict', models.CharField(max_length=20)),
            ],
        ),
    ]
